# Generated by Django 4.0.4 on 2022-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifacts',
            name='aDateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artifacts',
            name='aName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='artifacts',
            name='aPower',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factions',
            name='fLeader',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factions',
            name='fName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factions',
            name='fage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='levels',
            name='difficulty',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='levels',
            name='lName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='levels',
            name='lNpcAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='levels',
            name='lStructureAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stalkers',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stalkers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stalkers',
            name='faction',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stalkers',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stalkers',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
