# Generated by Django 4.0.4 on 2022-05-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0002_artifacts_adateofbirth_artifacts_aname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factions',
            old_name='fLeader',
            new_name='fFounder',
        ),
    ]
