# Generated by Django 4.0.4 on 2022-05-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0004_rename_fage_factions_fage_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
