# Generated by Django 4.0.4 on 2022-05-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0005_remove_avatar_image_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalkers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(verbose_name='Fecha de Creacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appChernobyl.stalkers')),
            ],
        ),
    ]
