# Generated by Django 4.0.4 on 2022-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0008_rename_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalkers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
