# Generated by Django 4.0.4 on 2022-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0015_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('advantage', models.CharField(max_length=100, null=True)),
                ('disavantage', models.CharField(max_length=100, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Artifacts',
        ),
    ]
