# Generated by Django 4.0.4 on 2022-05-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0017_rename_disavantage_artifact_disadvantage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stalkers',
            new_name='Stalker',
        ),
    ]
