# Generated by Django 4.0.4 on 2022-05-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0018_rename_stalkers_stalker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('founder', models.CharField(max_length=30, null=True)),
                ('leader', models.CharField(max_length=30, null=True)),
                ('allies', models.CharField(max_length=100, null=True)),
                ('enemies', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Factions',
        ),
    ]
