# Generated by Django 4.0.4 on 2022-05-24 19:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0020_faction_neutral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo del Post')),
                ('description', models.TextField(default='Descripcion', max_length=100, verbose_name='Descripcion')),
                ('body', ckeditor.fields.RichTextField()),
                ('date', models.DateField(verbose_name='Fecha de Creacion')),
                ('referencial_image', models.ImageField(max_length=255, upload_to='imagenes/')),
                ('status', models.BooleanField(default=False, verbose_name='Publish/Not Publish')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appChernobyl.stalker')),
            ],
        ),
    ]
