# Generated by Django 4.0.4 on 2022-05-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0021_post1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
