# Generated by Django 4.0.4 on 2022-05-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0022_alter_post1_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
