# Generated by Django 4.0.4 on 2022-05-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0023_delete_post1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='appChernobyl.stalker'),
        ),
    ]
