# Generated by Django 4.0.4 on 2022-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0025_tag_alter_post_author_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='tags',
        ),
        migrations.AddField(
            model_name='post1',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='appChernobyl.tag'),
        ),
    ]
