# Generated by Django 4.0.4 on 2022-05-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0026_remove_post1_tags_post1_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
