# Generated by Django 4.0.4 on 2022-06-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0027_delete_post1_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stalker',
            name='email',
        ),
    ]
