# Generated by Django 4.0.4 on 2022-06-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobyl', '0028_remove_stalker_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
