# Generated by Django 4.0.4 on 2022-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobylBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Chernobyl Archives', max_length=255),
        ),
    ]
