# Generated by Django 4.0.4 on 2022-05-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobylBlog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
