# Generated by Django 4.0.4 on 2022-06-04 01:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChernobylBlog', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mariano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('discord', models.URLField()),
                ('youtube', models.URLField()),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
